"""empty message

Revision ID: 9de71651198c
Revises: 4a14745ef9f8
Create Date: 2024-04-02 20:52:13.322993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9de71651198c'
down_revision: Union[str, None] = '4a14745ef9f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('track', sa.Column('genius_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('track', 'genius_url')
    # ### end Alembic commands ###
